Feature/button component
isdi-coders-2023/coding-adventure-Gaston-Artaza-front-202301-BCN pull request #1
Opened 2023-02-27 16:18 UTC by Gaston82

[x] Button test
[x] Button styles
[x] Button HTML

2023-02-27 16:23 UTC, MMLORENA requested changes

2023-02-27 16:23 UTC, MMLORENA commented on src/components/Button/Button.test.tsx
> +    test("Then it should show the text received", () => {
¿Qué texto recibe?

2023-02-27 16:23 UTC, MMLORENA commented on src/components/Button/Button.test.tsx
> +      expect(button).toBeInTheDocument();
Enter

2023-02-27 16:48 UTC, Gaston82 commented on src/components/Button/Button.test.tsx
> +    test("Then it should show the text received", () => {
Es Sign up en realidad. Ahora lo cambio

2023-02-27 16:49 UTC, Gaston82 commented on src/index.css
> +button {
Ok, ahora creo un GlobalStyle con los reset generales y fuentes

2023-02-27 16:52 UTC, Gaston82 commented on src/components/Button/Button.tsx
> +import ButtonStyled from "./ButtonStyled";
Aquí me pides un enter entre la línea uno y dos?

2023-02-27 17:13 UTC, MMLORENA requested changes

2023-02-27 17:13 UTC, MMLORENA commented on src/App.tsx
> +  return <Button text={"Sign up"} />;
El enunciado no habla de renderizarlo en App

2023-02-27 17:13 UTC, MMLORENA commented on src/components/Button/Button.tsx
> +import ButtonStyled from "./ButtonStyled";
Entre los imports y la interfaz

2023-02-28 11:20 UTC, Gaston82 commented
@MMLORENA @benjaminrae  PR actualizada

2023-02-28 11:22 UTC, benjaminrae commented
@Gaston82 Falla el audit

2023-02-28 11:26 UTC, benjaminrae requested changes

2023-02-28 11:26 UTC, benjaminrae commented on src/App.tsx
> +  return <Button text={"Sign up"} />;
@Gaston82 Y esto?

2023-02-28 11:26 UTC, benjaminrae commented on src/components/Button/Button.test.tsx
> +    test("Then it should show the text received", () => {
@Gaston82 No veo el cambio

2023-02-28 11:26 UTC, benjaminrae commented on src/components/Button/ButtonStyled.tsx
> +  background-color: #cccf18;
Debemos extraer los colores y otro CSS que se repite a un unico lugar

2023-02-28 11:26 UTC, benjaminrae commented on src/index.css
> +@import url("../node_modules/@fontsource/saira-stencil-one/index.css");
Asi no importamos un fuente instalado

2023-02-28 11:36 UTC, Gaston82 commented on src/components/Button/ButtonStyled.tsx
> +  background-color: #cccf18;
No lo había agregado a la request. Ahora lo agrego

2023-02-28 11:41 UTC, Gaston82 commented
@benjaminrae cambios actualizados

2023-02-28 11:53 UTC, Gaston82 commented
@benjaminrae indentaciones corregidas

2023-02-28 11:54 UTC, benjaminrae approved these changes

2023-02-28 11:54 UTC, benjaminrae commented on src/index.css
> +@import url("../node_modules/@fontsource/saira-stencil-one/index.css");
@Gaston82 Falta cambiar este import

2023-02-28 11:59 UTC, Gaston82 commented
@benjaminrae index.css borrado

2023-02-28 12:01 UTC, MMLORENA approved these changes

2023-02-28 12:01 UTC, merged